# Generated by Django 2.1 on 2019-07-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=40, verbose_name='nivel')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=40, verbose_name='nivel')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('municipality_id', models.ManyToManyField(to='states_app.Municipality', verbose_name='Municipio')),
            ],
        ),
    ]
